# equipos.py

NFL_TEAM_IDS = {
    "Arizona Cardinals": 22, "Atlanta Falcons": 1, "Baltimore Ravens": 33,
    "Buffalo Bills": 2, "Carolina Panthers": 29, "Chicago Bears": 3,
    "Cincinnati Bengals": 4, "Cleveland Browns": 5, "Dallas Cowboys": 6,
    "Denver Broncos": 7, "Detroit Lions": 8, "Green Bay Packers": 9,
    "Houston Texans": 34, "Indianapolis Colts": 11, "Jacksonville Jaguars": 30,
    "Kansas City Chiefs": 12, "Las Vegas Raiders": 13, "Los Angeles Chargers": 24,
    "Los Angeles Rams": 14, "Miami Dolphins": 15, "Minnesota Vikings": 16,
    "New England Patriots": 17, "New Orleans Saints": 18, "New York Giants": 19,
    "New York Jets": 20, "Philadelphia Eagles": 21, "Pittsburgh Steelers": 23,
    "San Francisco 49ers": 25, "Seattle Seahawks": 26, "Tampa Bay Buccaneers": 27,
    "Tennessee Titans": 10, "Washington Commanders": 28
}

NBA_TEAM_IDS = {
    "Atlanta Hawks": 1, "Boston Celtics": 2, "Brooklyn Nets": 17,
    "Charlotte Hornets": 30, "Chicago Bulls": 4, "Cleveland Cavaliers": 5,
    "Dallas Mavericks": 6, "Denver Nuggets": 7, "Detroit Pistons": 8,
    "Golden State Warriors": 9, "Houston Rockets": 10, "Indiana Pacers": 11,
    "LA Clippers": 12, "Los Angeles Lakers": 13, "Memphis Grizzlies": 29,
    "Miami Heat": 14, "Milwaukee Bucks": 15, "Minnesota Timberwolves": 16,
    "New Orleans Pelicans": 3, "New York Knicks": 18, "Oklahoma City Thunder": 25,
    "Orlando Magic": 19, "Philadelphia 76ers": 20, "Phoenix Suns": 21,
    "Portland Trail Blazers": 22, "Sacramento Kings": 23, "San Antonio Spurs": 24,
    "Toronto Raptors": 28, "Utah Jazz": 26, "Washington Wizards": 27
}

ESPN_SOCCER_LEAGUES = {
    "Premier League": "eng.1",
    "LaLiga EA Sports": "esp.1",
    "Bundesliga": "ger.1",
    "Serie A": "ita.1",
    "Champions League": "uefa.champions",
    "UEFA Nations League": "uefa.nations"
}

NATIONS_TROPHY_SVG = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 120'><path d='M30 110 L70 110 L65 85 C65 85 75 50 82 20 L18 20 C25 50 35 85 35 85 Z' fill='%23C0C0C0' stroke='%23333' stroke-width='2'/><path d='M25 25 C40 35 60 15 75 25 L70 40 C55 30 45 45 30 35 Z' fill='%234A5568'/><path d='M28 42 C43 52 57 32 72 42 L68 57 C53 47 43 62 32 52 Z' fill='%2310B981'/><path d='M32 59 C47 69 55 49 68 59 L65 74 C50 64 42 79 34 69 Z' fill='%23EF4444'/><circle cx='50' cy='98' r='6' fill='%23D97706'/></svg>"

LOGOS_LIGAS = {
    "Premier League": "https://a.espncdn.com/i/leaguelogos/soccer/500/23.png",
    "LaLiga EA Sports": "https://a.espncdn.com/i/leaguelogos/soccer/500/15.png",
    "UEFA Nations League": NATIONS_TROPHY_SVG,
    "Champions League": "https://a.espncdn.com/i/leaguelogos/soccer/500/2.png",
    "Bundesliga": "https://a.espncdn.com/i/leaguelogos/soccer/500/10.png",
    "Serie A": "https://a.espncdn.com/i/leaguelogos/soccer/500/12.png",
    "NFL": "https://upload.wikimedia.org/wikipedia/en/a/a2/National_Football_League_logo.svg",
    "MLB": "https://upload.wikimedia.org/wikipedia/commons/a/a6/Major_League_Baseball_logo.svg",
    "NBA": "https://upload.wikimedia.org/wikipedia/en/0/03/National_Basketball_Association_logo.svg"
}

PREMIER_DICT = {
    "Arsenal": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png", 
    "Aston Villa": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
    "AFC Bournemouth": "https://a.espncdn.com/i/teamlogos/soccer/500/349.png", 
    "Brentford": "https://a.espncdn.com/i/teamlogos/soccer/500/337.png",
    "Brighton & Hove Albion": "https://a.espncdn.com/i/teamlogos/soccer/500/331.png", 
    "Chelsea": "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
    "Crystal Palace": "https://a.espncdn.com/i/teamlogos/soccer/500/384.png", 
    "Everton": "https://a.espncdn.com/i/teamlogos/soccer/500/368.png",
    "Fulham": "https://a.espncdn.com/i/teamlogos/soccer/500/370.png", 
    "Ipswich Town": "https://a.espncdn.com/i/teamlogos/soccer/500/373.png",
    "Leicester City": "https://a.espncdn.com/i/teamlogos/soccer/500/375.png", 
    "Liverpool": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
    "Manchester City": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png", 
    "Manchester United": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
    "Newcastle United": "https://a.espncdn.com/i/teamlogos/soccer/500/361.png", 
    "Nottingham Forest": "https://a.espncdn.com/i/teamlogos/soccer/500/393.png",
    "Southampton": "https://a.espncdn.com/i/teamlogos/soccer/500/376.png", 
    "Tottenham Hotspur": "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
    "West Ham United": "https://a.espncdn.com/i/teamlogos/soccer/500/371.png", 
    "Wolverhampton": "https://a.espncdn.com/i/teamlogos/soccer/500/380.png"
}

LALIGA_DICT = {
    "Athletic Club": "https://a.espncdn.com/i/teamlogos/soccer/500/93.png", 
    "Atlético de Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
    "CA Osasuna": "https://a.espncdn.com/i/teamlogos/soccer/500/97.png", 
    "CD Leganés": "https://a.espncdn.com/i/teamlogos/soccer/500/9855.png",
    "Celta de Vigo": "https://a.espncdn.com/i/teamlogos/soccer/500/85.png", 
    "Deportivo Alavés": "https://a.espncdn.com/i/teamlogos/soccer/500/96.png",
    "FC Barcelona": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png", 
    "Getafe CF": "https://a.espncdn.com/i/teamlogos/soccer/500/2922.png",
    "Girona FC": "https://a.espncdn.com/i/teamlogos/soccer/500/9812.png", 
    "Rayo Vallecano": "https://a.espncdn.com/i/teamlogos/soccer/500/101.png",
    "RCD Espanyol": "https://a.espncdn.com/i/teamlogos/soccer/500/88.png", 
    "RCD Mallorca": "https://a.espncdn.com/i/teamlogos/soccer/500/84.png",
    "Real Betis": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png", 
    "Real Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
    "Real Sociedad": "https://a.espncdn.com/i/teamlogos/soccer/500/89.png", 
    "Sevilla FC": "https://a.espncdn.com/i/teamlogos/soccer/500/243.png",
    "Valencia CF": "https://a.espncdn.com/i/teamlogos/soccer/500/94.png", 
    "Real Valladolid": "https://a.espncdn.com/i/teamlogos/soccer/500/95.png",
    "Villarreal CF": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png", 
    "UD Las Palmas": "https://a.espncdn.com/i/teamlogos/soccer/500/98.png"
}

NATIONS_LEAGUE_DICT = {
    "España": "https://a.espncdn.com/i/teamlogos/countries/500/esp.png",
    "Francia": "https://a.espncdn.com/i/teamlogos/countries/500/fra.png",
    "Alemania": "https://a.espncdn.com/i/teamlogos/countries/500/ger.png",
    "Inglaterra": "https://a.espncdn.com/i/teamlogos/countries/500/eng.png",
    "Portugal": "https://a.espncdn.com/i/teamlogos/countries/500/por.png",
    "Italia": "https://a.espncdn.com/i/teamlogos/countries/500/ita.png",
    "Países Bajos": "https://a.espncdn.com/i/teamlogos/countries/500/ned.png",
    "Bélgica": "https://a.espncdn.com/i/teamlogos/countries/500/bel.png",
    "Croacia": "https://a.espncdn.com/i/teamlogos/countries/500/cro.png",
    "Dinamarca": "https://a.espncdn.com/i/teamlogos/countries/500/den.png",
    "Suiza": "https://a.espncdn.com/i/teamlogos/countries/500/sui.png",
    "Austria": "https://a.espncdn.com/i/teamlogos/countries/500/aut.png",
    "Hungría": "https://a.espncdn.com/i/teamlogos/countries/500/hun.png",
    "Polonia": "https://a.espncdn.com/i/teamlogos/countries/500/pol.png",
    "Escocia": "https://a.espncdn.com/i/teamlogos/countries/500/sco.png",
    "Serbia": "https://a.espncdn.com/i/teamlogos/countries/500/srb.png",
    "Israel": "https://a.espncdn.com/i/teamlogos/countries/500/isr.png",
    "Bosnia y Herzegovina": "https://a.espncdn.com/i/teamlogos/countries/500/bih.png",
    "República Checa": "https://a.espncdn.com/i/teamlogos/countries/500/cze.png",
    "Gales": "https://a.espncdn.com/i/teamlogos/countries/500/wal.png",
    "Finlandia": "https://a.espncdn.com/i/teamlogos/countries/500/fin.png",
    "Ucrania": "https://a.espncdn.com/i/teamlogos/countries/500/ukr.png",
    "Islandia": "https://a.espncdn.com/i/teamlogos/countries/500/isl.png",
    "Noruega": "https://a.espncdn.com/i/teamlogos/countries/500/nor.png",
    "Eslovenia": "https://a.espncdn.com/i/teamlogos/countries/500/svn.png",
    "Irlanda": "https://a.espncdn.com/i/teamlogos/countries/500/irl.png",
    "Albania": "https://a.espncdn.com/i/teamlogos/countries/500/alb.png",
    "Georgia": "https://a.espncdn.com/i/teamlogos/countries/500/geo.png",
    "Grecia": "https://a.espncdn.com/i/teamlogos/countries/500/gre.png",
    "Turquía": "https://a.espncdn.com/i/teamlogos/countries/500/tur.png",
    "Kazajistán": "https://a.espncdn.com/i/teamlogos/countries/500/kaz.png",
    "Montenegro": "https://a.espncdn.com/i/teamlogos/countries/500/mne.png",
    "Suecia": "https://a.espncdn.com/i/teamlogos/countries/500/swe.png",
    "Rumanía": "https://a.espncdn.com/i/teamlogos/countries/500/rou.png",
    "Armenia": "https://a.espncdn.com/i/teamlogos/countries/500/arm.png",
    "Luxemburgo": "https://a.espncdn.com/i/teamlogos/countries/500/lux.png",
    "Azerbaiyán": "https://a.espncdn.com/i/teamlogos/countries/500/aze.png",
    "Bulgaria": "https://a.espncdn.com/i/teamlogos/countries/500/bul.png",
    "Islas Feroe": "https://a.espncdn.com/i/teamlogos/countries/500/fro.png",
    "Macedonia del Norte": "https://a.espncdn.com/i/teamlogos/countries/500/mkd.png",
    "Eslovaquia": "https://a.espncdn.com/i/teamlogos/countries/500/svk.png",
    "Irlanda del Norte": "https://a.espncdn.com/i/teamlogos/countries/500/nir.png",
    "Chipre": "https://a.espncdn.com/i/teamlogos/countries/500/cyp.png",
    "Bielorrusia": "https://a.espncdn.com/i/teamlogos/countries/500/blr.png",
    "Lituania": "https://a.espncdn.com/i/teamlogos/countries/500/ltu.png",
    "Estonia": "https://a.espncdn.com/i/teamlogos/countries/500/est.png",
    "Letonia": "https://a.espncdn.com/i/teamlogos/countries/500/lva.png",
    "Kosovo": "https://a.espncdn.com/i/teamlogos/countries/500/kvx.png",
    "Moldavia": "https://a.espncdn.com/i/teamlogos/countries/500/mda.png",
    "Malta": "https://a.espncdn.com/i/teamlogos/countries/500/mlt.png",
    "Andorra": "https://a.espncdn.com/i/teamlogos/countries/500/and.png", 
    "San Marino": "https://a.espncdn.com/i/teamlogos/countries/500/smr.png",
    "Liechtenstein": "https://a.espncdn.com/i/teamlogos/countries/500/lie.png",
    "Gibraltar": "https://a.espncdn.com/i/teamlogos/countries/500/gib.png"
}

BUNDESLIGA_DICT = {
    "Bayern Múnich": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
    "Bayer Leverkusen": "https://a.espncdn.com/i/teamlogos/soccer/500/131.png",
    "Borussia Dortmund": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png", 
    "RB Leipzig": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
    "Eintracht Frankfurt": "https://a.espncdn.com/i/teamlogos/soccer/500/125.png", 
    "VfB Stuttgart": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
    "SC Freiburg": "https://a.espncdn.com/i/teamlogos/soccer/500/126.png", 
    "Union Berlin": "https://a.espncdn.com/i/teamlogos/soccer/500/130.png",
    "Borussia Mönchengladbach": "https://a.espncdn.com/i/teamlogos/soccer/500/128.png", 
    "Werder Bremen": "https://a.espncdn.com/i/teamlogos/soccer/500/137.png",
    "FC Augsburgo": "https://a.espncdn.com/i/teamlogos/soccer/500/3812.png", 
    "TSG Hoffenheim": "https://a.espncdn.com/i/teamlogos/soccer/500/7911.png",
    "Mainz 05": "https://a.espncdn.com/i/teamlogos/soccer/500/129.png", 
    "VfL Wolfsburgo": "https://a.espncdn.com/i/teamlogos/soccer/500/138.png",
    "Heidenheim": "https://a.espncdn.com/i/teamlogos/soccer/500/10363.png", 
    "VfL Bochum": "https://a.espncdn.com/i/teamlogos/soccer/500/123.png",
    "St. Pauli": "https://a.espncdn.com/i/teamlogos/soccer/500/268.png", 
    "Holstein Kiel": "https://a.espncdn.com/i/teamlogos/soccer/500/8066.png"
}

SERIE_A_DICT = {
    "Inter de Milán": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
    "Juventus": "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
    "AC Milan": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
    "Napoli": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
    "AS Roma": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
    "Atalanta": "https://a.espncdn.com/i/teamlogos/soccer/500/105.png",
    "Lazio": "https://a.espncdn.com/i/teamlogos/soccer/500/112.png",
    "Fiorentina": "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
    "Bologna": "https://a.espncdn.com/i/teamlogos/soccer/500/107.png",
    "Torino": "https://a.espncdn.com/i/teamlogos/soccer/500/239.png",
    "Monza": "https://a.espncdn.com/i/teamlogos/soccer/500/3614.png",
    "Genoa": "https://a.espncdn.com/i/teamlogos/soccer/500/3263.png",
    "Parma": "https://a.espncdn.com/i/teamlogos/soccer/500/113.png",
    "Udinese": "https://a.espncdn.com/i/teamlogos/soccer/500/118.png",
    "Cagliari": "https://a.espncdn.com/i/teamlogos/soccer/500/108.png", 
    "Hellas Verona": "https://a.espncdn.com/i/teamlogos/soccer/500/238.png",
    "Empoli": "https://a.espncdn.com/i/teamlogos/soccer/500/240.png",
    "Lecce": "https://a.espncdn.com/i/teamlogos/soccer/500/3452.png",
    "Como 1907": "https://a.espncdn.com/i/teamlogos/soccer/500/2625.png",
    "Venezia": "https://a.espncdn.com/i/teamlogos/soccer/500/2744.png"
}

CHAMPIONS_DICT = {
    "Paris Saint-Germain": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",
    "Bayern Múnich": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
    "FC Barcelona": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
    "Manchester United": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
    "Como 1907": "https://a.espncdn.com/i/teamlogos/soccer/500/2625.png",
    "Sporting CP": "https://a.espncdn.com/i/teamlogos/soccer/500/300.png",
    "VfB Stuttgart": "https://a.espncdn.com/i/teamlogos/soccer/500/134.png",
    "Manchester City": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
    "Aston Villa": "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
    "RC Lens": "https://a.espncdn.com/i/teamlogos/soccer/500/166.png",
    "Real Betis": "https://a.espncdn.com/i/teamlogos/soccer/500/244.png",
    "Borussia Dortmund": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
    "Liverpool": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
    "Real Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
    "Arsenal": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
    "AEK Athens": "https://a.espncdn.com/i/teamlogos/soccer/500/448.png",
    "AS Roma": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png",
    "Shakhtar Donetsk": "https://a.espncdn.com/i/teamlogos/soccer/500/438.png",
    "Fenerbahçe": "https://a.espncdn.com/i/teamlogos/soccer/500/436.png",
    "PSV Eindhoven": "https://a.espncdn.com/i/teamlogos/soccer/500/148.png",
    "Villarreal CF": "https://a.espncdn.com/i/teamlogos/soccer/500/102.png",
    "Club Brujas": "https://a.espncdn.com/i/teamlogos/soccer/500/2282.png",
    "Lille OSC": "https://a.espncdn.com/i/teamlogos/soccer/500/162.png",
    "Slavia Praha": "https://a.espncdn.com/i/teamlogos/soccer/500/439.png",
    "Atlético de Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
    "Inter de Milán": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
    "LASK": "https://a.espncdn.com/i/teamlogos/soccer/500/3282.png",
    "Napoli": "https://a.espncdn.com/i/teamlogos/soccer/500/114.png",
    "Galatasaray": "https://a.espncdn.com/i/teamlogos/soccer/500/437.png",
    "Viking FK": "https://a.espncdn.com/i/teamlogos/soccer/500/2324.png",
    "FC Porto": "https://a.espncdn.com/i/teamlogos/soccer/500/298.png",
    "RB Leipzig": "https://a.espncdn.com/i/teamlogos/soccer/500/11420.png",
    "Feyenoord": "https://a.espncdn.com/i/teamlogos/soccer/500/142.png",
    "Sabah FK": "https://a.espncdn.com/i/teamlogos/soccer/500/20340.png",
    "Slovan Bratislava": "https://a.espncdn.com/i/teamlogos/soccer/500/2322.png",
    "Bodø/Glimt": "https://a.espncdn.com/i/teamlogos/soccer/500/10365.png"
}

NBA_DICT = {
    "Atlanta Hawks": {"abbr": "atl", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/atl.png", "pace": 101.2, "hca": 2.2},
    "Boston Celtics": {"abbr": "bos", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/bos.png", "pace": 98.8, "hca": 2.8},
    "Brooklyn Nets": {"abbr": "bkn", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png", "pace": 97.5, "hca": 2.1},
    "Charlotte Hornets": {"abbr": "cha", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/cha.png", "pace": 99.1, "hca": 2.0},
    "Chicago Bulls": {"abbr": "chi", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/chi.png", "pace": 100.5, "hca": 2.3},
    "Cleveland Cavaliers": {"abbr": "cle", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/cle.png", "pace": 97.2, "hca": 2.6},
    "Dallas Mavericks": {"abbr": "dal", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/dal.png", "pace": 96.8, "hca": 2.5},
    "Denver Nuggets": {"abbr": "den", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/den.png", "pace": 97.1, "hca": 4.0},
    "Detroit Pistons": {"abbr": "det", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/det.png", "pace": 98.6, "hca": 2.0},
    "Golden State Warriors": {"abbr": "gsw", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/gsw.png", "pace": 100.1, "hca": 2.9},
    "Houston Rockets": {"abbr": "hou", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/hou.png", "pace": 99.4, "hca": 2.4},
    "Indiana Pacers": {"abbr": "ind", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/ind.png", "pace": 102.8, "hca": 2.3},
    "LA Clippers": {"abbr": "lac", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/lac.png", "pace": 97.4, "hca": 2.2},
    "Los Angeles Lakers": {"abbr": "lal", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/lal.png", "pace": 100.8, "hca": 2.7},
    "Memphis Grizzlies": {"abbr": "mem", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/mem.png", "pace": 100.2, "hca": 2.5},
    "Miami Heat": {"abbr": "mia", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/mia.png", "pace": 96.5, "hca": 2.6},
    "Milwaukee Bucks": {"abbr": "mil", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/mil.png", "pace": 100.4, "hca": 2.8},
    "Minnesota Timberwolves": {"abbr": "min", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/min.png", "pace": 97.8, "hca": 2.6},
    "New Orleans Pelicans": {"abbr": "nop", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/nop.png", "pace": 98.2, "hca": 2.2},
    "New York Knicks": {"abbr": "nyk", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/nyk.png", "pace": 95.8, "hca": 2.7},
    "Oklahoma City Thunder": {"abbr": "okc", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/okc.png", "pace": 99.7, "hca": 2.8},
    "Orlando Magic": {"abbr": "orl", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/orl.png", "pace": 97.0, "hca": 2.5},
    "Philadelphia 76ers": {"abbr": "phi", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/phi.png", "pace": 96.9, "hca": 2.6},
    "Phoenix Suns": {"abbr": "phx", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/phx.png", "pace": 98.1, "hca": 2.4},
    "Portland Trail Blazers": {"abbr": "por", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/por.png", "pace": 98.5, "hca": 2.2},
    "Sacramento Kings": {"abbr": "sac", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/sac.png", "pace": 99.6, "hca": 2.5},
    "San Antonio Spurs": {"abbr": "sas", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/sas.png", "pace": 101.0, "hca": 2.2},
    "Toronto Raptors": {"abbr": "tor", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/tor.png", "pace": 99.3, "hca": 2.3},
    "Utah Jazz": {"abbr": "uta", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/uta.png", "pace": 100.6, "hca": 3.5},
    "Washington Wizards": {"abbr": "was", "logo": "https://a.espncdn.com/i/teamlogos/nba/500/was.png", "pace": 102.1, "hca": 1.9}
}

EQUIPOS_MLB = {
    "Arizona Diamondbacks": {"abbr": "ari", "id": 109, "wRC_plus": 105, "park_factor": 1.02},
    "Atlanta Braves": {"abbr": "atl", "id": 144, "wRC_plus": 115, "park_factor": 1.01},
    "Baltimore Orioles": {"abbr": "bal", "id": 110, "wRC_plus": 112, "park_factor": 0.98},
    "Boston Red Sox": {"abbr": "bos", "id": 111, "wRC_plus": 106, "park_factor": 1.05},
    "Chicago Cubs": {"abbr": "chc", "id": 112, "wRC_plus": 103, "park_factor": 1.00},
    "Chicago White Sox": {"abbr": "cws", "id": 145, "wRC_plus": 84, "park_factor": 0.98},
    "Cincinnati Reds": {"abbr": "cin", "id": 113, "wRC_plus": 98, "park_factor": 1.06},
    "Cleveland Guardians": {"abbr": "cle", "id": 114, "wRC_plus": 101, "park_factor": 0.96},
    "Colorado Rockies": {"abbr": "col", "id": 115, "wRC_plus": 91, "park_factor": 1.15},
    "Detroit Tigers": {"abbr": "det", "id": 116, "wRC_plus": 97, "park_factor": 0.97},
    "Houston Astros": {"abbr": "hou", "id": 117, "wRC_plus": 113, "park_factor": 0.99},
    "Kansas City Royals": {"abbr": "kc", "id": 118, "wRC_plus": 102, "park_factor": 1.02},
    "Los Angeles Angels": {"abbr": "laa", "id": 108, "wRC_plus": 95, "park_factor": 0.99},
    "Los Angeles Dodgers": {"abbr": "lad", "id": 119, "wRC_plus": 120, "park_factor": 1.01},
    "Miami Marlins": {"abbr": "mia", "id": 146, "wRC_plus": 89, "park_factor": 0.95},
    "Milwaukee Brewers": {"abbr": "mil", "id": 158, "wRC_plus": 101, "park_factor": 1.01},
    "Minnesota Twins": {"abbr": "min", "id": 142, "wRC_plus": 104, "park_factor": 1.00},
    "New York Mets": {"abbr": "nym", "id": 121, "wRC_plus": 109, "park_factor": 0.96},
    "New York Yankees": {"abbr": "nyy", "id": 147, "wRC_plus": 118, "park_factor": 1.02},
    "Oakland Athletics": {"abbr": "oak", "id": 133, "wRC_plus": 96, "park_factor": 0.95},
    "Philadelphia Phillies": {"abbr": "phi", "id": 143, "wRC_plus": 114, "park_factor": 1.03},
    "Pittsburgh Pirates": {"abbr": "pit", "id": 134, "wRC_plus": 93, "park_factor": 0.97},
    "San Diego Padres": {"abbr": "sd", "id": 135, "wRC_plus": 107, "park_factor": 0.95},
    "San Francisco Giants": {"abbr": "sf", "id": 137, "wRC_plus": 97, "park_factor": 0.94},
    "Seattle Mariners": {"abbr": "sea", "id": 136, "wRC_plus": 98, "park_factor": 0.92},
    "St. Louis Cardinals": {"abbr": "stl", "id": 138, "wRC_plus": 98, "park_factor": 0.98},
    "Tampa Bay Rays": {"abbr": "tb", "id": 139, "wRC_plus": 100, "park_factor": 0.95},
    "Texas Rangers": {"abbr": "tex", "id": 140, "wRC_plus": 105, "park_factor": 1.02},
    "Toronto Blue Jays": {"abbr": "tor", "id": 141, "wRC_plus": 102, "park_factor": 0.99},
    "Washington Nationals": {"abbr": "wsh", "id": 120, "wRC_plus": 94, "park_factor": 1.01}
}

DICT_NFL_COMPLETO = {
    "Arizona Cardinals": {"abbr": "ARI", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png", "off": 21.5, "def": 24.2},
    "Atlanta Falcons": {"abbr": "ATL", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png", "off": 22.8, "def": 21.9},
    "Baltimore Ravens": {"abbr": "BAL", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png", "off": 27.1, "def": 18.5},
    "Buffalo Bills": {"abbr": "BUF", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png", "off": 26.5, "def": 19.2},
    "Carolina Panthers": {"abbr": "CAR", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/car.png", "off": 16.2, "def": 25.8},
    "Chicago Bears": {"abbr": "CHI", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png", "off": 20.1, "def": 22.3},
    "Cincinnati Bengals": {"abbr": "CIN", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png", "off": 24.8, "def": 23.1},
    "Cleveland Browns": {"abbr": "CLE", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png", "off": 19.5, "def": 21.0},
    "Dallas Cowboys": {"abbr": "DAL", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png", "off": 26.2, "def": 22.1},
    "Denver Broncos": {"abbr": "DEN", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png", "off": 21.0, "def": 20.5},
    "Detroit Lions": {"abbr": "DET", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png", "off": 28.5, "def": 20.2},
    "Green Bay Packers": {"abbr": "GB", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png", "off": 24.5, "def": 21.0},
    "Houston Texans": {"abbr": "HOU", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png", "off": 23.1, "def": 19.8},
    "Indianapolis Colts": {"abbr": "IND", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png", "off": 22.4, "def": 23.5},
    "Jacksonville Jaguars": {"abbr": "JAX", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png", "off": 21.2, "def": 23.8},
    "Kansas City Chiefs": {"abbr": "KC", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png", "off": 25.8, "def": 17.5},
    "Las Vegas Raiders": {"abbr": "LV", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png", "off": 18.2, "def": 24.1},
    "Los Angeles Chargers": {"abbr": "LAC", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png", "off": 22.0, "def": 19.2},
    "Los Angeles Rams": {"abbr": "LAR", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png", "off": 23.8, "def": 22.5},
    "Miami Dolphins": {"abbr": "MIA", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png", "off": 25.0, "def": 22.8},
    "Minnesota Vikings": {"abbr": "MIN", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png", "off": 24.1, "def": 20.4},
    "New England Patriots": {"abbr": "NE", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png", "off": 17.1, "def": 22.0},
    "New Orleans Saints": {"abbr": "NO", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/no.png", "off": 22.5, "def": 21.8},
    "New York Giants": {"abbr": "NYG", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png", "off": 17.8, "def": 23.9},
    "New York Jets": {"abbr": "NYJ", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png", "off": 18.0, "def": 19.8},
    "Philadelphia Eagles": {"abbr": "PHI", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png", "off": 26.1, "def": 20.8},
    "Pittsburgh Steelers": {"abbr": "PIT", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png", "off": 20.5, "def": 18.8},
    "San Francisco 49ers": {"abbr": "SF", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png", "off": 27.8, "def": 19.1},
    "Seattle Seahawks": {"abbr": "SEA", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png", "off": 22.9, "def": 22.4},
    "Tampa Bay Buccaneers": {"abbr": "TB", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png", "off": 24.2, "def": 22.0},
    "Tennessee Titans": {"abbr": "TEN", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png", "off": 18.9, "def": 23.1},
    "Washington Commanders": {"abbr": "WAS", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/was.png", "off": 24.8, "def": 23.5}
}
